-- Ethereum
-- Token Transfer
COPY INTO @~/eth_token_transfer/
FROM (
  SELECT *
  FROM ETHEREUM_ONCHAIN_CORE_DATA.CORE.EZ_TOKEN_TRANSFERS
)
FILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY)
SINGLE = FALSE
MAX_FILE_SIZE = 536870912   -- ~512 MB compressed
OVERWRITE = TRUE;

LIST @~/eth_token_transfer/;

-- Native Transfer
COPY INTO @~/eth_native_transfer/
FROM (
  SELECT *
  FROM ETHEREUM_ONCHAIN_CORE_DATA.CORE.EZ_NATIVE_TRANSFERS
)
FILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY)
SINGLE = FALSE
MAX_FILE_SIZE = 536870912   -- ~512 MB compressed
OVERWRITE = TRUE;

LIST @~/eth_native_transfer/;

-- Label
COPY INTO @~/eth_label/
FROM (
  SELECT *
  FROM ETHEREUM_ONCHAIN_CORE_DATA.CORE.DIM_LABELS
)
FILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY)
SINGLE = FALSE
MAX_FILE_SIZE = 536870912   -- ~512 MB compressed
OVERWRITE = TRUE;

LIST @~/eth_label/;

-- Contract
COPY INTO @~/eth_contract/
FROM (
  SELECT *
  FROM ETHEREUM_ONCHAIN_CORE_DATA.CORE.DIM_CONTRACTS
)
FILE_FORMAT = (TYPE = PARQUET COMPRESSION = SNAPPY)
SINGLE = FALSE
MAX_FILE_SIZE = 536870912   -- ~512 MB compressed
OVERWRITE = TRUE;

LIST @~/eth_contract/;
